### ISSUE TITLE
Need some Code Change ( No attribute drop_prop and full_layers)

### ISSUE THREAD

**Issue by s4sarath** [mhjabreel/CharCNN#1]
Hi ,

Change in training.py char_cnn.drop_prop to char_cnn.drop_keep_prob and
Change in training.py CharCNN class attribute "full_layers" to "fully_layers" .

**Comment by mhjabreel** [comment]
Hi s4sarath,

Thank you for your feedback, the problem was that I did a mistake by uploading the first version that I was working on, I have solve the issue, thank you again, please let me know if there is any another issue.

**Comment by s4sarath** [comment]
Sure . Good thing that you open sourced it . Helpful to a lot.
