### ISSUE TITLE
Memory leak issue in Tensorflow 

### ISSUE THREAD

**Issue by Unilord** [mhjabreel/CharCNN#10]
My system slows down everytime I run the code, when I looked it online, I found an issue regarding memory leak in Tensorflow. https://github.com/tensorflow/tensorflow/issues/10408 , The least I could understand was that should you not use `sess.close()`  and `tf.reset_default_graph()` in training.py after the training loop at the end.

**Comment by mhjabreel** [comment]
Hi @Unilord,
Now, you can use the new implementation in the branch textify_bases. 
The problem is solved. I checked that and now it works.

Thanks.
