### ISSUE TITLE
why input_layer size is 1014

### ISSUE THREAD

**Issue by luckystar1992** [mhjabreel/CharCNN#12]
hi,
Why you set the input layer size equal to 1014 and in your another code repository CharCnn_Keras, you   
put a config.json file, is that a config file of caffee or torch? thanks.

**Comment by mhjabreel** [comment]
Hi @luckystar1992,
This is just a parameter represents the maximum length of the text, you can adjust it as you want. The value 1014 was chosen by the authors of the paper. They claimed that the most important and informative features that can distinguish the topics of texts can be found in the first 1014.  

Best.
