### ISSUE TITLE
data reproducibility

### ISSUE THREAD

**Issue by jeremied3** [mhjabreel/CharCNN#4]
Hi,

 I've tried to reproduce Zhang et al.'s result using your code (downloaded and run as is) but obtain very low accuracy numbers (25%) not at all near the paper's reported numbers.
Have you managed to reproduce their numbers?

**Comment by renzhe0009** [comment]
Please see https://github.com/mhjabreel/CharCNN/issues/3 .
That's all we know.

**Comment by jeremied3** [comment]
Thanks, that is very helpful! I will change the optimizer to momentum and try again.
